version: "3.8"

networks:
  personal-vpc:
    name: personal-vpc
    external: false
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.10.50.0/24
          ip_range: 10.10.50.0/24
          gateway: 10.10.50.100

services:
  personal-website:
    image: node:18-alpine
    container_name: personal-website
    restart: unless-stopped
    networks:
      - personal-vpc
    volumes:
      - type: bind
        source: ./
        target: /app
    working_dir: /app
    command:
      - sh
      - -c
      - |
        npm install
        npm run dev
    environment:
      - NODE_ENV=development
      - PORT=5000
      - HOST=0.0.0.0