version: "3.8"

networks:
  orb-core:
    name: orb-core
    driver: bridge
    external: true

services:
  prv-personal-svelte:
    image: node:18-alpine
    container_name: prv-personal-svelte
    restart: unless-stopped
    networks:
      - orb-core
    volumes:
      - type: bind
        source: ./
        target: /app
    working_dir: /app
    command:
      - sh
      - -c
      - |
        npm install
        npm run dev
    environment:
      - NODE_ENV=development
      - PORT=5000
      - HOST=0.0.0.0